### ISSUE TITLE
Top 5 component

### ISSUE THREAD

**Issue by logancostello** [AquaJet738/307-team-project#14]
Display the top 5 (artists/tracks/genre/album).

1. Take in argument "artist" or "track" or "genre" or "album"
2. Spotify API call to get the top 5, or use one of the functions we made for genres and albums
3. Display the information in an interesting way

Could be the number, name, and their picture from spotify

Make the component as reusable as possible

**Comment by AquaJet738** [comment]
Top 5 component implemented into home page redesign
