### ISSUE TITLE
Top Albums Function

### ISSUE THREAD

**Issue by logancostello** [AquaJet738/307-team-project#18]
Using the users top tracks, calculate their top albums.

Make a function that does this and return the albums sorted. try to keep as much information as possible, so not just the album names but also album art, artist, etc. basically whatever spotify gives you

**Comment by AquaJet738** [comment]
Completed by Logan. Function returns album objects (in JSON)

**Comment by AquaJet738** [comment]
Expected time: 2 hrs
Actual time: 4 hrs
