### ISSUE TITLE
Figma Design

### ISSUE THREAD

**Issue by logancostello** [AquaJet738/307-team-project#9]
Design the project on figma

**Comment by nathanlim1** [comment]
Link to figma design: https://www.figma.com/proto/B1oJXpPLf7JzFuQCopd3L1/nlim10's-team-library?node-id=3340-2&t=LIE9UKYDyIBDWZoJ-1

**Comment by nathanlim1** [comment]
EST time for home page - 1 hr
ACTUAL time for home page - 2 hrs

**Comment by luke-villaluz** [comment]
estimated 1 hr
actual 1 hr 30 mins

**Comment by AquaJet738** [comment]
For login page:
Estimated time: 30 min
Actual time: 20 min
